# Generated by Django 3.2.6 on 2022-01-15 05:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211218_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 5, 46, 4, 48213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 5, 46, 4, 47212, tzinfo=utc)),
        ),
    ]
