# Generated by Django 3.2.6 on 2022-02-05 04:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220115_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 4, 32, 25, 228101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 4, 32, 25, 228101, tzinfo=utc)),
        ),
    ]
